### ISSUE TITLE
DFS

### ISSUE THREAD

**Issue by abirbhattacharya82** [abirbhattacharya82/Hacktoberfest22-DSA-CP-Code-Dump#10]
Implement Depth First Search in any Language

**Comment by Aditya0049** [comment]
implemented

**Comment by Mohammed-Saif0** [comment]
Hey!! I would love to work on this issue, **I will demonstrate Depth First Search (DFS) in both trees and graphs**. Please kindly assign this to me :wink:

**Comment by Mohammed-Saif0** [comment]
thank <3

**Comment by Yh010** [comment]
I would like to work on this issue. Could u pls assign this issue?
