### ISSUE TITLE
Fibonacci sequence using Java

### ISSUE THREAD

**Issue by dhruvpatidar359** [abirbhattacharya82/Hacktoberfest22-DSA-CP-Code-Dump#36]
Write a Program(Code) in Java to Print the Fibonacci Sequence

**Comment by dhruvpatidar359** [comment]
kindly assign me this issue

**Comment by abirbhattacharya82** [comment]
You are good to go

**Comment by SanjaySargam** [comment]
Can I contribute in this ?

**Comment by UnnatKr** [comment]
@dhruvpatidar359 please assign me this
